first commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,24 +101,33 @@ jobs:
 
           set +e          # 关闭自动退出
 
-          pylint  -f parseable --rcfile=./.github/config/.pylintrc --persistent=n $FILES ## || true  ##运行 pylint 检查代码规范
+          pylint  -f parseable --rcfile=./.github/config/.pylintrc --persistent=n $FILES  PYLINT_EXIT=$?
 
-          # curl -X POST \
-          #   -H "Accept: application/vnd.github+json" \
-          #   -H "Authorization: Bearer $GITHUB_TOKEN" \
-          #   https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs \
-          #   -d "{
-          #     \"name\": \"Pylint Check\",
-          #     \"head_sha\": \"$GITHUB_SHA\",
-          #     \"status\": \"completed\",
-          #     \"conclusion\": \"neutral\",
-          #     \"completed_at\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
-          #     \"output\": {
-          #       \"title\": \"Pylint Result\",
-          #       \"summary\": \"Some warnings detected.\"
-          #     }
-          #   }"
-          
+          echo "Pylint exit code: $PYLINT_EXIT"
+          if [ $PYLINT_EXIT == 0 ]; then
+            echo "✅ Pylint passed"
+            exit 0
+          elif [ $PYLINT_EXIT == 20 ]; then
+            echo "⚠️ Pylint found errors or warnings"
+            curl -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer $GITHUB_TOKEN" \
+              https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs \
+              -d "{
+                \"name\": \"Pylint Check\",
+                \"head_sha\": \"$GITHUB_SHA\",
+                \"status\": \"completed\",
+                \"conclusion\": \"neutral\",
+                \"completed_at\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
+                \"output\": {
+                  \"title\": \"Pylint Result\",
+                  \"summary\": \"Some warnings detected.\"
+                }
+              }"
+            else
+              echo "❌ Pylint failed"
+              exit $PYLINT_EXIT
+            fi
 
       - name: Show neutral status
 
